### PR TITLE
Remove gen-typescript-declarations and add .d.ts to repo with manual changes.

### LINKED ISSUE #52: IronA11yAnnouncer.requestAvailability static method missing from TypeScript .d.ts file.
`iron-a11y-announcer.d.ts` is missing an entry for the static `IronA11yAnnouncer.requestAvailability()` method. This was discovered while investigating using TypeScript in Chromium's WebUI codebase, and we had to add this manually for now with the following diff

```diff
diff --git a/third_party/polymer/v3_0/components-chromium/iron-a11y-announcer/iron-a11y-announcer.d.ts b/third_party/polymer/v3_0/components-chromium/iron-a11y-announcer/iron-a11y-announcer.d.ts
index b60ac3ba18a0..1646ce15f0f0 100644
--- a/third_party/polymer/v3_0/components-chromium/iron-a11y-announcer/iron-a11y-announcer.d.ts
+++ b/third_party/polymer/v3_0/components-chromium/iron-a11y-announcer/iron-a11y-announcer.d.ts
@@ -34,6 +34,7 @@ declare class IronA11yAnnouncer {
    */
   announce(text: string): void;
   _onIronAnnounce(event: any): void;
+  static requestAvailability(): void;
 }
 
 interface IronA11yAnnouncer extends LegacyElementMixin, HTMLElement {
```

@usergenic 
I believe this file is generated automatically at [1], and therefore possibly a bug in the `gen-typescript-declarations` tool itself?

[1] https://github.com/PolymerElements/iron-a11y-announcer/blob/master/package.json#L27

### PR DESCRIPTION
**Pull request by usergenic**
The `gen-typescript-declarations` tool which was used to dynamically generate the typescript declarations for this element is no longer being actively maintained.  There was a missing declaration needed, so this PR adds that manually to the generated .d.ts file and adds the .d.ts file directly to the repo, while removing the script and the `gen-typescript-declarations` dependency.

This fixes the issue reported in #52.

### CODE REVIEW

**Review by e111077 — APPROVED** [review]

**Comment by usergenic** [comment]
Thanks @ e111077

**Review by e111077 — APPROVED** [review]

**Comment by usergenic** [comment]
YAY tests finally passing after switching distro to xenial and downgrading npm to 6.

**Review by e111077 — APPROVED** [review]

**Comment by e111077** [comment]
You are magic! 🧙

**Comment by usergenic** [comment]
You are!

**Pull request merged**
